### PR TITLE
fix: send json accept headers for POST requests

### PR DESCRIPTION
**Pull request by BryanttV**
### Description

This PR solves a CORS error when calling the endpoints for **Changing Site Language** and **Unlinking the SSO Account**. To resolve this error we simply specify the `Accept: 'application/json'` header in the request.

These are the related issues:
- https://github.com/openedx/frontend-app-account/issues/1052
- https://github.com/openedx/wg-build-test-release/issues/376

### Testing Instructions

The changes have been tested in a local environment with **Tutor v18.1.3**.

1. In your Tutor environment clone the Account MFE with these changes.
2. Create a mount with `tutor mounts add frontend-app-account`
3. Run `tutor dev start -d` to recreate the containers.
4. Inside the Account MFE folder run `npm install`
5. Finally run `tutor dev restart`

#### Changing Site Language
1. Go to the **Account Settings** > **Site Preferences**.
2. Click **Edit** next to **Site language**.
3. Pick a language.
4. Click **Save**.
5. CORS error does not appear.

#### Unlinking the SSO Account
1. Configure TPA auth for Open edX.
2. Login or Register via third-party authentication.
3. Go to **Account Settings** > **Linked Accounts**
4. Click Unlink {TPA_Name} account.
5. CORS error does not appear.

### Screenshots

| Before | After |
|--------|--------|
| image | image |
| image | image |

#### Merge Checklist

* [ ] If your update includes visual changes, have they been reviewed by a designer? Send them a link to the Sandbox, if applicable.
* [ ] Is there adequate test coverage for your changes?

#### Post-merge Checklist

* [ ] Deploy the changes to prod after verifying on stage or ask **@openedx/edx-infinity** to do it. 
* [ ] 🎉 🙌 Celebrate! Thanks for your contribution.

### CODE REVIEW

**Comment by BryanttV** [comment]
Hi! @mariajgrimaldi @arbrandes, here is the solution to correct the CORS error. I look forward to any questions or comments.

**Comment by BryanttV** [comment]
Hi @mariajgrimaldi @arbrandes, Although this change fixes the CORS error, according to the tests I did locally the language is still not being changed until the page is reloaded.

**Comment by BryanttV** [comment]
Hi, @mariajgrimaldi @arbrandes. I did another test using a [tutor plugin](https://github.com/overhangio/tutor-mfe/?tab=readme-ov-file#adding-new-mfes) instead of a mount. Now, it updates the language without reloading the page. I'm not sure why the mount doesn't work.

https://github.com/user-attachments/assets/673102b9-67c2-403d-ac2a-d8c52d38db4e

I switched to each language and as reported in the [issue](https://github.com/openedx/frontend-app-account/issues/1052), some don't work.
- en ✅
- ar ✅
- ca ❌ (Switches to English automatically)
- es-419 ✅
- fa-ir ✅
- fr ❌ (Switches to English automatically)
- he ✅
- id ✅ (But the [translation file](https://github.com/openedx/openedx-translations/blob/main/translations/frontend-app-account/src/i18n/messages/id.json) is not in Indonesian (?))
- ko-kr ❌ (Switches to English automatically)
- pl ❌ (Switches to English automatically)
- pt-br ✅
- ru ✅
- th ✅
- uk ✅
- zh-cn ✅
- pt-pt ✅
- it-it ✅
- de-de ✅
- hi ✅
- fr-ca ✅
- te ✅
- da ✅
- el ✅
- es-es ✅
- sw ✅
- tr-tr ✅

None of the 4 failing ones is [here](https://github.com/openedx/openedx-translations/tree/main/translations/frontend-app-account/src/i18n/messages).

**Comment by mariajgrimaldi** [comment]
Great news, @BryanttV! Thank you so much for testing this out. I'll try to get someone to review this ASAP.

**Comment by arbrandes** [comment]
Starting to review now.

**Review by arbrandes — APPROVED** [review]
I tested this, and it works!  Thank you!

**Pull request merged**
