### PR TITLE
feat: add toggling for the hardcode support link (for master)

### PR DESCRIPTION
**Pull request by DmytroAlipov**
### Description:
Add a toggling mechanism for the `unlink all social media accounts` text to display it as a link or text depending on the MFE env setting.
Currently, the link leads to the page *https://support.edx.org/hc/en-us/articles/207206067* which is hardcoded. I suggest adding the `DISABLE_UNLINK_SOCIAL_MEDIA_ACCOUNT_SUPPORT_URL` variable to control whether this text is displayed as a link or as plain text.

Before:
screen_75

After:
screen_76

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @DmytroAlipov!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by e0d** [comment]
@DmytroAlipov Looks like there are some linting failures, https://github.com/openedx/frontend-app-account/actions/runs/6048702918/job/16519629022?pr=864#step:7:20, Can you have a look?

**Comment by DmytroAlipov** [comment]
@e0d done

**Review by Syed-Ali-Abbas-Zaidi — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@DmytroAlipov 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-account&entry.867055334=https://github.com/openedx/frontend-app-account/pull/864&entry.1484655318=https://github.com/DmytroAlipov&entry.752974735=2023-08-31+14:01&entry.1917517419=2023-09-21+08:28&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
