### PR TITLE
Allow disable account deletion

### PR DESCRIPTION
**Pull request by JonasBM**
Referenced issue: [There is no way to disable account deletion in the Account MFE #189](https://github.com/openedx/wg-build-test-release/issues/189)

Add environment variable `ENABLE_ACCOUNT_DELETION`, to allow the disable of account deletion.
To disable account deletion set `ENABLE_ACCOUNT_DELETION="false"`, otherwise it will default to true.

Updated JumpNav test to include the no render of account deletion components.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @JonasBM!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by JonasBM** [comment]
About the test, i just updated the existing one. If necessary i can create two other tests just for this feature.

**Comment by JonasBM** [comment]
Fixed linting errors.

**Comment by mphilbrick211** [comment]
Hi @JonasBM! Is this all set for review?

**Comment by JonasBM** [comment]
Hi, @mphilbrick211! Yes.
I think that to complete solve the issue there is a back-end change that should be done. But for that I will post in the forum and discuss before any change.
For the front-end (this change) I is all good for a review.

**Comment by mphilbrick211** [comment]
Hi @openedx/fed-bom! Could someone please review/merge this for us? Thanks!

**Comment by JonasBM** [comment]
About this solution, i have some questions that i post in the forum, please give a read, especially if this PR is accepted.
[Solving the issue for disable account deletion in the Account MFE](https://discuss.openedx.org/t/solving-the-issue-for-disable-account-deletion-in-the-account-mfe/10684)

**Comment by mphilbrick211** [comment]
Hi @openedx/fed-bom! Would someone be able to review/merge this for us? Thanks!

**Comment by mphilbrick211** [comment]
Apologies, @abdullahwaheed - I see you already plan to review - thanks!

**Review by abdullahwaheed — APPROVED** [review]

**Comment by mariajgrimaldi** [comment]
Hi there, @abdullahwaheed. What do we need to merge this PR?

**Comment by JonasBM** [comment]
Fixed a conflict in the merge.

**Comment by mphilbrick211** [comment]
Hi @abdullahwaheed! Would you be able to enable tests again for this PR?

**Comment by abdullahwaheed** [comment]
@JonasBM could you please resolve conflicts so we can merge this PR

**Comment by abdullahwaheed** [comment]
@JonasBM just another suggestion. Could you update Readme accordingly so we have a proper documentation of this flag and its functionality

**Comment by openedx-webhooks** [comment]
@JonasBM 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-account&entry.867055334=https://github.com/openedx/frontend-app-account/pull/817&entry.1484655318=https://github.com/JonasBM&entry.752974735=2023-07-05+18:42&entry.1917517419=2023-08-28+10:40&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
