### PR TITLE
chore(i18n): add more languages

### PR DESCRIPTION
**Pull request by Yoiber071**
Add Transifex Working Group languages.

New language codes: it_IT,pt_PT,de_DE

@feanil 
@natabene

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Yoiber071!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by e0d** [comment]
@mphilbrick211 Tests run.

**Comment by e0d** [comment]
@Yoiber071 looks like there are test failures.

**Comment by abdullahwaheed** [comment]
@Yoiber071 tests are failing in this PR. could you please fix the issues

**Comment by abdullahwaheed** [comment]
@Yoiber071 any updates on this?

**Comment by Yoiber071** [comment]
Hi @abdullahwaheed, Sorry for the late response, I've fixed the lint failures, and is ready to be tested again.

**Review by abdullahwaheed — COMMENTED** [review]
Looks good to me. @feanil, @natabene do you want to review it?

**Comment by openedx-webhooks** [comment]
@Yoiber071 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-account&entry.867055334=https://github.com/openedx/frontend-app-account/pull/747&entry.1484655318=https://github.com/Yoiber071&entry.752974735=2023-02-14+16:12&entry.1917517419=2023-03-06+14:13&entry.2133058324=No) so we can improve your experience in the future.

**Comment by e0d** [comment]
Sorry, hit the wrong button, reopening.

**Review by abdullahwaheed — APPROVED** [review]

**Comment by mphilbrick211** [comment]
@openedx/fed-bom would someone be so kind as to merge this?

**Review by Syed-Ali-Abbas-Zaidi — APPROVED** [review]

**Review by BilalQamar95 — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@Yoiber071 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-account&entry.867055334=https://github.com/openedx/frontend-app-account/pull/747&entry.1484655318=https://github.com/Yoiber071&entry.752974735=2023-02-14+16:12&entry.1917517419=2023-03-09+13:45&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
