### PR TITLE
fix: Fixed the display of the selection of available time zones

### PR DESCRIPTION
**Pull request by DmytroAlipov**
### Description

An error was found when selecting a timezone in the user account.

In this [PR](https://github.com/openedx/frontend-app-account/pull/27), a time zone selection was added.
Then the select field was rewritten in [PR](https://github.com/openedx/frontend-app-account/pull/612). (Paragon form component deprecations)
However, these changes have broken the time zone selection field.

#### Before:

screen_91

screen_94

#### After:

screen_93

screen_92

### CODE REVIEW

**Comment by DmytroAlipov** [comment]
Could you please advise on what to do with test coverage? Before my pull request, the file _frontend-app-account/src/account-settings/test/EditableSelectField.test.jsx_ had no test coverage at all. I added tests for this file, but the coverage actually decreased.

**Comment by heldersepu** [comment]
@DmytroAlipov take a look at the indirect changes in CodeCov:
https://app.codecov.io/gh/openedx/frontend-app-account/pull/896/indirect-changes

**Comment by DmytroAlipov** [comment]
@heldersepu done!

**Review by heldersepu — APPROVED** [review]

**Review by Mashal-m — APPROVED** [review]
LGTM

**Comment by mphilbrick211** [comment]
Hi @Mashal-m! Are you able to merge this for us, along with its backport #895 ? Thanks!

**Comment by DmytroAlipov** [comment]
@mphilbrick211 just a friendly ping :)

**Comment by mphilbrick211** [comment]
Thanks, @DmytroAlipov! I believe @openedx/2u-fed-bom and @Mashal-m might be out for the holidays, but pinging again just in case.

**Review by abdullahwaheed — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@DmytroAlipov 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-account&entry.867055334=https://github.com/openedx/frontend-app-account/pull/896&entry.1484655318=https://github.com/DmytroAlipov&entry.752974735=2023-10-04+13:53&entry.1917517419=2024-01-01+18:07&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
