### PR TITLE
feat: remove usage of scss variables

### PR DESCRIPTION
**Pull request by xitij2000**
Remove usage of SCSS variables so that the MFE doesn't need SCSS variables at build-time.

Screenshots before and after this PR:
| Before | After |
|---|---|
|Screenshot_20220509_140129|Screenshot_20220509_140030|
|Screenshot_20220509_140253|Screenshot_20220509_140309|
|Screenshot_20220509_140433|Screenshot_20220509_140422|
|Screenshot_20220509_140916|Screenshot_20220509_140904|

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @xitij2000! I've created [OSPR-6662](https://openedx.atlassian.net/browse/OSPR-6662) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@xitij2000 Thank you for your contribution. Is this ready for our review?

**Review by davidjoy — APPROVED** [review]
Great work.  Love to see this getting cleaned up! 😍

**Comment by davidjoy** [comment]
[inform] I'm merging a PR to upgrade this MFE to node 16, so am pausing on merging this just so I can keep my deploys separated.  Hope to merge shortly once I can prove the upgrade worked.

**Review by tecoholic — APPROVED** [review]
:+1:

- [x] I tested this: Verified that changes are as expected in the UI.
- [x] I read through the code
- [x] I checked for accessibility issues
- [ ] Includes documentation - NA

**Comment by xitij2000** [comment]
> [inform] I'm merging a PR to upgrade this MFE to node 16, so am pausing on merging this just so I can keep my deploys separated. Hope to merge shortly once I can prove the upgrade worked.

Sure, you'll see PRs from me or others from OpenCraft with similar cleanups. 

I had created a prototype version of having a common theme build centrally and loaded in multiple MFEs. I was hoping to set up a demo version of that soon, but currently our deployment pipeline needs fixes. 

Here is that PR with the prototype: https://github.com/openedx/frontend-app-discussions/pull/125

**Comment by openedx-webhooks** [comment]
@xitij2000 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-account&entry.867055334=https://github.com/openedx/frontend-app-account/pull/601&entry.1484655318=https://github.com/xitij2000&entry.752974735=2022-05-06+10:40&entry.1917517419=2022-05-16+19:41&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
