### PR TITLE
feat: make password reset support URL configurable

### PR DESCRIPTION
**Pull request by dyudyunov**
Replace the hardcoded `support.edx.org` value with the one from the env vars.

Either the link to the support page or support email (with `mailto:<email_address>` could be used.)

There are also account verification and account deletion messages containing hardcoded `edx.org` links/emails which might be fixed in the future

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @dyudyunov!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by dyudyunov** [comment]
@mphilbrick211 this one is ready for review, I'll open the backport PR to Olive with similar changes soon

**Comment by mphilbrick211** [comment]
@dyudyunov - I'll get these tests run for you.

**Comment by e0d** [comment]
@mphilbrick211 tests running.

**Comment by dyudyunov** [comment]
@e0d could you run workflows again, I've just pushed a fix for the lining error

**Comment by mphilbrick211** [comment]
@jmbowman Hi there! Could you please review (and merge if all looks good)? Thanks! 

CC: @openedx/fed-bom

**Review by abdullahwaheed — APPROVED** [review]
looks good. i think we should also update all the hard-coded links to config based

**Comment by mphilbrick211** [comment]
Hi @abdullahwaheed - would you mind getting this merged if it's all set?

**Comment by abdullahwaheed** [comment]
@mphilbrick211 i'll have to update its config in edx-internal as well otherwise the link will break in stage and prod. i'll create that PR tomorrow and i'll merge this one after that config PR will be merged.

**Comment by openedx-webhooks** [comment]
@dyudyunov 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-account&entry.867055334=https://github.com/openedx/frontend-app-account/pull/745&entry.1484655318=https://github.com/dyudyunov&entry.752974735=2023-02-13+11:19&entry.1917517419=2023-03-02+06:46&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
