### PR TITLE
feat: add support for design tokens and CSS variables

### PR DESCRIPTION
**Pull request by xitij2000**
WIP: Adds support for styling using a runtime theming as implemented in  https://github.com/openedx/frontend-platform/pull/440

### CODE REVIEW

**Comment by mphilbrick211** [comment]
Hi @xitij2000! Just seeing if this is OK to close?

**Comment by xitij2000** [comment]
> Hi @xitij2000! Just seeing if this is OK to close?

This is laying groundwork for the design tokens work going in https://github.com/openedx/frontend-platform/pull/440

**Comment by Mashal-m** [comment]
Hey @xitij2000, What is the current status of this PR, is it ready to review and merge? 
Could you please resolve conflicts?

**Comment by mphilbrick211** [comment]
> Hey @xitij2000, What is the current status of this PR, is it ready to review and merge? Could you please resolve conflicts?

Hi @xitij2000 - just following up to see if this can be closed?

**Comment by xitij2000** [comment]
> > Hey @xitij2000, What is the current status of this PR, is it ready to review and merge? Could you please resolve conflicts?
> 
> Hi @xitij2000 - just following up to see if this can be closed?

I'll close it for now and reopen when the relevant PR https://github.com/openedx/frontend-platform/pull/440 is merged.

**Comment by mphilbrick211** [comment]
Closing per comment above.

**Comment by openedx-webhooks** [comment]
@xitij2000 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-account&entry.867055334=https://github.com/openedx/frontend-app-account/pull/862&entry.1484655318=https://github.com/xitij2000&entry.752974735=2023-08-28+10:36&entry.1917517419=2024-01-16+22:25&entry.2133058324=No) so we can improve your experience in the future.

**Comment by openedx-webhooks** [comment]
@xitij2000 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-account&entry.867055334=https://github.com/openedx/frontend-app-account/pull/862&entry.1484655318=https://github.com/xitij2000&entry.752974735=2023-08-28+10:36&entry.1917517419=2024-01-16+22:25&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
