### PR TITLE
Conditionally Display "Delete Account" in Account Settings

### PR DESCRIPTION
**Pull request by AdamKing0126**
Load value `ENABLE_ACCOUNT_DELETION` from .env to conditionally display the "delete account" Account Setting

This is a possible solution to the issue outlined here: https://github.com/openedx/wg-build-test-release/issues/189

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @AdamKing0126!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/openedx/.github/blob/master/CONTRIBUTING.md)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

    
Once you've signed the CLA, please allow 1 business day for it to be processed.  After this time, you can re-run the     CLA check by editing the PR title.  If the problem persists, you can tag the `@openedx/cla-problems` team in a     comment on your PR for further assistance.

**Comment by e0d** [comment]
@AdamKing0126 I've approved the tests, but wanted to make sure that you saw the message about the CLA above.

**Comment by e0d** [comment]
I notice there are some commit-lint failures.  Please note that we use conventional commits across Open edX projects.  You can read about the details [here](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0051-bp-conventional-commits.html#type).  Can you please amend your commit messages to follow our standard?

**Comment by e0d** [comment]
Also looks like there are some test failures that need attention.

**Comment by mphilbrick211** [comment]
hi @AdamKing0126! Just following up to see if you are planning to re-run the failing tests? Please let us know if you have any questions. Thanks!

**Comment by mphilbrick211** [comment]
> hi @AdamKing0126! Just following up to see if you are planning to re-run the failing tests? Please let us know if you have any questions. Thanks!

Hi @AdamKing0126 - checking in to see if you plan to pursue this pull request? If so, we'll need a signed CLA from you. Please let me know if you have any questions. Thanks!

**Comment by mphilbrick211** [comment]
> > hi @AdamKing0126! Just following up to see if you are planning to re-run the failing tests? Please let us know if you have any questions. Thanks!
> 
> Hi @AdamKing0126 - checking in to see if you plan to pursue this pull request? If so, we'll need a signed CLA from you. Please let me know if you have any questions. Thanks!

Hi @AdamKing0126 - please let us know if you plan to pursue this pull request. Thanks!

**Comment by mphilbrick211** [comment]
Hi @AdamKing0126! I'm going to close this for now due to inactivity. If you'd like to pursue in the future, we can reopen it. Thanks!

**Comment by openedx-webhooks** [comment]
@AdamKing0126 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-account&entry.867055334=https://github.com/openedx/frontend-app-account/pull/799&entry.1484655318=https://github.com/AdamKing0126&entry.752974735=2023-06-03+02:12&entry.1917517419=2023-09-12+14:04&entry.2133058324=No) so we can improve your experience in the future.

**Comment by openedx-webhooks** [comment]
@AdamKing0126 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-account&entry.867055334=https://github.com/openedx/frontend-app-account/pull/799&entry.1484655318=https://github.com/AdamKing0126&entry.752974735=2023-06-03+02:12&entry.1917517419=2023-09-12+14:04&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
