### PR TITLE
chore: Persian translations updated

### PR DESCRIPTION
**Pull request by CodeWithEmad**
Persian Translations have been updated to this pull request as of August 7th, 2023.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @CodeWithEmad!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by mphilbrick211** [comment]
Hi @openedx/fed-bom! Would someone be able to review/merge this for us? Thanks!

**Comment by abdullahwaheed** [comment]
@CodeWithEmad we have an automated bot that sync up languages from transifex. #843 has synced up persian language. Closing this one now since its changes have already been merged

**Comment by CodeWithEmad** [comment]
That's interesting.
Contributors may not be aware of everything.
Is there any documentation available that I missed?

**Pull request closed without merging**
