### PR TITLE
feat:  allow runtime configuration

### PR DESCRIPTION
**Pull request by dcoa**
**Description**

This PR allows the app to change the favicon and the site name in the title tag at runtime and serves as a discussion.

This is part of a work to make it possible to configure the frontend applications at runtime (you can referer to this [**FWG issue**](https://github.com/openedx/frontend-wg/issues/103)). 

**This PR depend on https://github.com/openedx/frontend-platform/pull/335**

The changes are grouped in a component Head, that uses Helmet library and integrates internationalization to change the MFE name in the title tag according to the language.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @dcoa! I've created [OSPR-6719](https://openedx.atlassian.net/browse/OSPR-6719) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by natabene** [comment]
@dcoa Thank you for your contribution. Please let me know once it is ready for our review.

**Comment by dcoa** [comment]
Hi @natabene  this PR is ready for our review.

**Comment by MaferMazu** [comment]
@arbrandes I think you might like to take a look at this.

**Review by davidjoy — CHANGES_REQUESTED** [review]
The `i18n/messages/*.json` files should not be updated manually - they are generated and will be overridden and updated by the transifex/translations jobs.  The new English language messages.js file content is sufficient. 👍🏻 

I think this looks good otherwise.

**Comment by dcoa** [comment]
Yes, PR does not affect the actual app behavior but I wonder if it's better to use this to change the dependency once frontend-platform has been updated and backport only 1 commit to the nutmeg release.

**Comment by robrap** [comment]
@davidjoy: Will you be merging this?

**Comment by davidjoy** [comment]
From @dcoa's comment above, I think we're waiting to use this PR to update the frontend-platform dependency once https://github.com/openedx/frontend-platform/pull/335 merges.  @dcoa, let me know if that's not what you intended and I can just merge this!

**Comment by dcoa** [comment]
Hi, @davidjoy @arbrandes someone has already fixed the peer dependency error, and I was able to update the `package.json` and `package-lock.json` the PR is ready with all changes, Could you run the test and review it? 
Thanks :)

**Comment by davidjoy** [comment]
Argh - it says the branch has conflicts that must be resolved but isn't showing which files.  Apologies, that may be because of the delay in review and something else went into the master branch.  

I just tested this, seems to work well.  If we can get that conflict resolved I'll push the merge button.

**Comment by dcoa** [comment]
Hi hi 🖖, now the conflict is resolved. 😊

**Comment by openedx-webhooks** [comment]
@dcoa 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-account&entry.867055334=https://github.com/openedx/frontend-app-account/pull/603&entry.1484655318=https://github.com/dcoa&entry.752974735=2022-05-25+00:41&entry.1917517419=2022-08-09+17:44&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
