### PR TITLE
feat: make password reset support URL configurable

### PR DESCRIPTION
**Pull request by dyudyunov**
Replace the hardcoded `support.edx.org` value with the one from the env vars.

This is a backport of #745

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @dyudyunov!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by dyudyunov** [comment]
@mphilbrick211 this one is ready for review)

**Comment by e0d** [comment]
@mphilbrick211 test running.

**Comment by dyudyunov** [comment]
@e0d please run the workflow again, I've fixed a listing error

**Comment by e0d** [comment]
@mphilbrick211 all set with this one.

**Comment by mphilbrick211** [comment]
@jmbowman @openedx/fed-bom - would you please take a look and merge if all looks good? Thanks!

**Review by abdullahwaheed — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@dyudyunov 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-account&entry.867055334=https://github.com/openedx/frontend-app-account/pull/746&entry.1484655318=https://github.com/dyudyunov&entry.752974735=2023-02-13+11:23&entry.1917517419=2023-03-02+07:26&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
