### PR TITLE
fix: install error due to peer conflict

### PR DESCRIPTION
**Pull request by ghassanmas**
This fixes install error on node 16 and npm => 8.6.*
  The install error is due to confliect of peer dependecy.
  The project is using tensorflow-models/blazeface 0.0.7
  which require tensorflow/tfjs-converter and tensorflow/tfjs-core
  to be ^3.11.0 [ref](https://github.com/tensorflow/tfjs-models/blob/dcec078d66eb36e36cae516e1581d69d50d4fca3/blazeface/package.json#L15-L18)
 
Note: this might not have caused erros before, because probably npm older version didn't catch but it was suppose to.
Also this needs probably need to be backported to nutmeg. 

The error:
```
#35 9.604 npm ERR! code ERESOLVE
#35 9.609 npm ERR! ERESOLVE could not resolve
#35 9.611 npm ERR!
#35 9.612 npm ERR! While resolving: @tensorflow-models/blazeface@0.0.7
#35 9.613 npm ERR! Found: @tensorflow/tfjs-converter@1.7.4
#35 9.614 npm ERR! node_modules/@tensorflow/tfjs-converter
#35 9.614 npm ERR!   @tensorflow/tfjs-converter@"1.7.4" from the root project
#35 9.615 npm ERR!
#35 9.616 npm ERR! Could not resolve dependency:
#35 9.617 npm ERR! peer @tensorflow/tfjs-converter@"^3.1.0" from @tensorflow-models/blazeface@0.0.7
#35 9.617 npm ERR! node_modules/@tensorflow-models/blazeface
#35 9.618 npm ERR!   @tensorflow-models/blazeface@"0.0.7" from the root project
#35 9.619 npm ERR!
#35 9.620 npm ERR! Conflicting peer dependency: @tensorflow/tfjs-converter@3.18.0
#35 9.622 npm ERR! node_modules/@tensorflow/tfjs-converter
#35 9.623 npm ERR!   peer @tensorflow/tfjs-converter@"^3.1.0" from @tensorflow-models/blazeface@0.0.7
#35 9.624 npm ERR!   node_modules/@tensorflow-models/blazeface
#35 9.625 npm ERR!     @tensorflow-models/blazeface@"0.0.7" from the root project
#35 9.626 npm ERR!
#35 9.627 npm ERR! Fix the upstream dependency conflict, or retry
#35 9.627 npm ERR! this command with --force, or --legacy-peer-deps
#35 9.628 npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
#35 9.629 npm ERR!
#35 9.630 npm ERR! See /root/.npm/eresolve-report.txt for a full report.
#35 9.633
#35 9.633 npm ERR! A complete log of this run can be found in:
#35 9.634 npm ERR!     /root/.npm/_logs/2022-06-27T10_39_41_571Z-debug-0.log
```

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ghassanmas!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by ghassanmas** [comment]
Why this doesn't occur in edx: Because edx is using an older version of npm which doesn't check for validation, hence https://github.com/openedx/configuration/blob/87bda9669c59344729de65b422d0a5420d368fe2/playbooks/roles/edxapp/defaults/main.yml#L1108 .
Given since npm 8.6 or something npm started to validate pacakge-lock.json hence: https://github.com/npm/cli/issues/4664

**Comment by adamstankiewicz** [comment]
@ghassanmas The upgrade of these tensorflow packages is going from v1 to v3. Were there any breaking changes that needed to be addressed in this repo, or are the breaking changes in v2/v3 not relevant to this repo?

Also, FWIW, it looks like this repo has a `is-es5` check as part of its CI. This can be changed to actually validate against `is-es6` instead since we've dropped the requirement to support older browsers like IE 11 that rely on ES5-compatible code.

**Comment by ghassanmas** [comment]
> @ghassanmas The upgrade of these tensorflow packages is going from v1 to v3. Were there any breaking changes that needed to be addressed in this repo, or are the breaking changes in v2/v3 not relevant to this repo?

It shouldn't because to _my understanding_  This repo doesn't use tensorflow core nor tensorflow converter, they are added just as peer dependecy only I assume?. _When I searched in repo code, I can only find usage only for `'@tensorflow-models/blazeface'`_  which is not updated in this PR.  For reference here the official notes about the releases: 

- 1 to 2 [github](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v2.0.0) 
- 2 to 3 [github](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v3.0.0) [doc](https://www.tensorflow.org/js/tutorials/upgrading_to_3_0)
 
> Also, FWIW, it looks like this repo has a `is-es5` check as part of its CI. This can be changed to actually validate against `is-es6` instead since we've dropped the requirement to support older browsers like IE 11 that rely on ES5-compatible code.

I guess you mean here it needs simlair PR to [this](https://github.com/openedx/frontend-app-learning/commit/7f3757539adea1e2ffb2e29e1ef507f02f5f2e7e). Should I make simliar changes and then rebase this PR after is-es5 is removed?

**Comment by dcoa** [comment]
Hello, I think is-es5 is already removed https://github.com/openedx/frontend-app-account/commit/196719963fc33503ad2b9be297049adb39cb7a9c, and now you can rebase this branch to pass the test

**Comment by dcoa** [comment]
Hi @ghassanmas I think this PR could be closed due to someone updating the @tensorflow dependency and is in master now https://github.com/openedx/frontend-app-account/commit/0527c735295949c71074021b07530d2c70e38cb0

**Comment by openedx-webhooks** [comment]
@ghassanmas Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-account&entry.867055334=https://github.com/openedx/frontend-app-account/pull/611&entry.1484655318=https://github.com/ghassanmas&entry.752974735=2022-06-27+11:03&entry.1917517419=2022-07-28+19:58&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
